fix: deploy directly into the app directory and then unzip the client distribution.

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -125,7 +125,7 @@ jobs:
           username: ${{ github.event.inputs.server_user }}
           key: ${{ secrets.SERVER_SSH_KEY }}
           source: "${{ env.WEB_DIR }}/${{ env.WEB_ZIP_NAME }}"
-          target: "/home/${{ github.event.inputs.server_user }}/${{ secrets.APP_NAME }}/client/"
+          target: "/home/${{ github.event.inputs.server_user }}/${{ secrets.APP_NAME }}/"
           overwrite: true
 
       - name: SSH Deploy Web
@@ -135,9 +135,15 @@ jobs:
           username: ${{ github.event.inputs.server_user }}
           key: ${{ secrets.SERVER_SSH_KEY }}
           script: |
-            cd ~/${{ secrets.APP_NAME }}/client || exit 1
-            if [ -f ${{ env.WEB_ZIP_NAME }} ]; then sudo unzip -o ${{ env.WEB_ZIP_NAME }}; else echo "${{ env.WEB_ZIP_NAME }} not found!"; exit 1; fi
-
+            cd ~/${{ secrets.APP_NAME }} || exit 1
+            if [ -f ${{ env.WEB_ZIP_NAME }} ]; then
+              cd client || exit 1
+              sudo unzip -o ../${{ env.WEB_ZIP_NAME }}
+              cd ..
+            else
+              echo "${{ env.WEB_ZIP_NAME }} not found!"
+              exit 1
+            fi
   restart-services:
     runs-on: ubuntu-latest
     needs: deploy-web
