fix: Updates deployment paths and scripts

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -55,7 +55,7 @@ jobs:
           username: ${{ github.event.inputs.server_user }}
           key: ${{ secrets.SERVER_SSH_KEY }}
           source: "crm-api/dist.zip"
-          target: "/home/${{ github.event.inputs.server_user }}/crm/"
+          target: "/home/${{ github.event.inputs.server_user }}/"
           overwrite: true
 
       - name: SSH Deploy API
@@ -66,7 +66,12 @@ jobs:
           key: ${{ secrets.SERVER_SSH_KEY }}
           script: |
             cd ~/crm || exit 1
-            if [ -f dist.zip ]; then sudo unzip -o dist.zip; else echo "dist.zip not found!"; exit 1; fi
+            if [ -f ~/crm-api/dist.zip ]; then
+              sudo unzip -o ~/crm-api/dist.zip
+            else
+              echo "dist.zip not found!"
+              exit 1
+            fi
 
   deploy-web:
     runs-on: ubuntu-latest
@@ -118,7 +123,7 @@ jobs:
           username: ${{ github.event.inputs.server_user }}
           key: ${{ secrets.SERVER_SSH_KEY }}
           source: "crm-web/client-dist.zip"
-          target: "/home/${{ github.event.inputs.server_user }}/crm/"
+          target: "/home/${{ github.event.inputs.server_user }}/"
           overwrite: true
 
       - name: SSH Deploy Web
@@ -128,15 +133,14 @@ jobs:
           username: ${{ github.event.inputs.server_user }}
           key: ${{ secrets.SERVER_SSH_KEY }}
           script: |
-            cd ~/crm || exit 1
-            if [ -f client-dist.zip ]; then
-              cd client || exit 1
-              sudo unzip -o ../client-dist.zip
-              cd ..
+            cd ~/crm/client || exit 1
+            if [ -f ~/crm-web/client-dist.zip ]; then
+              sudo unzip -o ~/crm-web/client-dist.zip
             else
               echo "client-dist.zip not found!"
               exit 1
             fi
+
   restart-services:
     runs-on: ubuntu-latest
     needs: deploy-web
